AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: twimbot-poster

Globals:
    Function:
        Timeout: 10

Resources:
    TwimbotTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: !Ref DynamoDbTable
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: "S"
                - AttributeName: process_time
                  AttributeType: "N"
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            GlobalSecondaryIndexes:
                - IndexName: !Ref DynamoDbIndex
                  KeySchema:
                      - AttributeName: process_time
                        KeyType: HASH
                  Projection:
                      ProjectionType: "INCLUDE"
                      NonKeyAttributes:
                          - id
                          - title
                  ProvisionedThroughput:
                      ReadCapacityUnits: "1"
                      WriteCapacityUnits: "1"
            ProvisionedThroughput:
                ReadCapacityUnits: "1"
                WriteCapacityUnits: "1"
    TwimbotBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref S3Bucket
    TwimbotFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: twimbot_poster/
            Handler: app.lambda_handler
            Runtime: python3.9
            Architectures:
                - x86_64
            Environment:
                Variables:
                    DYNAMODB_INDEX: !Ref DynamoDbIndex
                    DYNAMODB_TABLE: !Ref DynamoDbTable
                    S3_BUCKET: !Ref S3Bucket
                    ACCESS_TOKEN: !Ref AccessToken
                    ACCESS_TOKEN_SECRET: !Ref AccessTokenSecret
                    CONSUMER_KEY: !Ref ConsumerKey
                    CONSUMER_SECRET: !Ref ConsumerSecret
            Policies:
                - Statement:
                      - Sid: S3ReadBucket
                        Effect: Allow
                        Action:
                            - s3:GetObject
                            - s3:ListBucket
                        Resource: !GetAtt TwimbotBucket.Arn
                - Statement:
                      - Sid: DynamoDBReadWriteTable
                        Effect: Allow
                        Action:
                            - dynamodb:GetItem
                            - dynamodb:Scan
                            - dynamodb:Query
                            - dynamodb:UpdateItem
                        Resource: !GetAtt TwimbotTable.Arn
    TwimbotRule:
        Type: AWS::Events::Rule
        Properties:
            ScheduleExpression: cron(00 17 ? * 7 *)
            Targets:
                - Arn: !GetAtt TwimbotFunction.Arn
                  Id: twimbot-post-target
Parameters:
    DynamoDbIndex:
        Type: String
    DynamoDbTable:
        Type: String
    S3Bucket:
        Type: String
    AccessToken:
        Type: String
    AccessTokenSecret:
        Type: String
    ConsumerKey:
        Type: String
    ConsumerSecret:
        Type: String
